config/routes.rb
Rails.application.routes.draw do
  resources :emp_records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emp_record.rb
class EmpRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emp_records_controller.rb
class EmpRecordsController < ApplicationController
  before_action :set_emp_record, only: [:show, :edit, :update, :destroy]

  # GET /emp_records
  # GET /emp_records.json
  def index
    @emp_records = EmpRecord.all
  end

  # GET /emp_records/1
  # GET /emp_records/1.json
  def show
  end

  # GET /emp_records/new
  def new
    @emp_record = EmpRecord.new
  end

  # GET /emp_records/1/edit
  def edit
  end

  # POST /emp_records
  # POST /emp_records.json
  def create
    @emp_record = EmpRecord.new(emp_record_params)

    respond_to do |format|
      if @emp_record.save
        format.html { redirect_to @emp_record, notice: 'Emp record was successfully created.' }
        format.json { render :show, status: :created, location: @emp_record }
      else
        format.html { render :new }
        format.json { render json: @emp_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emp_records/1
  # PATCH/PUT /emp_records/1.json
  def update
    respond_to do |format|
      if @emp_record.update(emp_record_params)
        format.html { redirect_to @emp_record, notice: 'Emp record was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp_record }
      else
        format.html { render :edit }
        format.json { render json: @emp_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emp_records/1
  # DELETE /emp_records/1.json
  def destroy
    @emp_record.destroy
    respond_to do |format|
      format.html { redirect_to emp_records_url, notice: 'Emp record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp_record
      @emp_record = EmpRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_record_params
      params.require(:emp_record).permit(:firstname, :middlename, :lastname, :address, :mobile, :landline, :email, :unit, :idnumber, :tin, :designation, :additionalinfo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emp_records_helper.rb
module EmpRecordsHelper
end

app/views/emp_records/_form.html.erb
<%= form_with(model: emp_record, local: true) do |form| %>
  <% if emp_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp_record.errors.count, "error") %> prohibited this emp_record from being saved:</h2>

      <ul>
      <% emp_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :emp_record_firstname %>
  </div>

  <div class="field">
    <%= form.label :middlename %>
    <%= form.text_field :middlename, id: :emp_record_middlename %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :emp_record_lastname %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :emp_record_address %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id: :emp_record_mobile %>
  </div>

  <div class="field">
    <%= form.label :landline %>
    <%= form.text_field :landline, id: :emp_record_landline %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :emp_record_email %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit, id: :emp_record_unit %>
  </div>

  <div class="field">
    <%= form.label :idnumber %>
    <%= form.text_field :idnumber, id: :emp_record_idnumber %>
  </div>

  <div class="field">
    <%= form.label :tin %>
    <%= form.text_field :tin, id: :emp_record_tin %>
  </div>

  <div class="field">
    <%= form.label :designation %>
    <%= form.text_field :designation, id: :emp_record_designation %>
  </div>

  <div class="field">
    <%= form.label :additionalinfo %>
    <%= form.text_area :additionalinfo, id: :emp_record_additionalinfo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emp_records/edit.html.erb
<h1>Editing Emp Record</h1>

<%= render 'form', emp_record: @emp_record %>

<%= link_to 'Show', @emp_record %> |
<%= link_to 'Back', emp_records_path %>

app/views/emp_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emp Records</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>Landline</th>
      <th>Email</th>
      <th>Unit</th>
      <th>Idnumber</th>
      <th>Tin</th>
      <th>Designation</th>
      <th>Additionalinfo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emp_records.each do |emp_record| %>
      <tr>
        <td><%= emp_record.firstname %></td>
        <td><%= emp_record.middlename %></td>
        <td><%= emp_record.lastname %></td>
        <td><%= emp_record.address %></td>
        <td><%= emp_record.mobile %></td>
        <td><%= emp_record.landline %></td>
        <td><%= emp_record.email %></td>
        <td><%= emp_record.unit %></td>
        <td><%= emp_record.idnumber %></td>
        <td><%= emp_record.tin %></td>
        <td><%= emp_record.designation %></td>
        <td><%= emp_record.additionalinfo %></td>
        <td><%= link_to 'Show', emp_record %></td>
        <td><%= link_to 'Edit', edit_emp_record_path(emp_record) %></td>
        <td><%= link_to 'Destroy', emp_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp Record', new_emp_record_path %>

app/views/emp_records/new.html.erb
<h1>New Emp Record</h1>

<%= render 'form', emp_record: @emp_record %>

<%= link_to 'Back', emp_records_path %>

app/views/emp_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @emp_record.firstname %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @emp_record.middlename %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @emp_record.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @emp_record.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @emp_record.mobile %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @emp_record.landline %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emp_record.email %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @emp_record.unit %>
</p>

<p>
  <strong>Idnumber:</strong>
  <%= @emp_record.idnumber %>
</p>

<p>
  <strong>Tin:</strong>
  <%= @emp_record.tin %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @emp_record.designation %>
</p>

<p>
  <strong>Additionalinfo:</strong>
  <%= @emp_record.additionalinfo %>
</p>

<%= link_to 'Edit', edit_emp_record_path(@emp_record) %> |
<%= link_to 'Back', emp_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employeerecord</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>